### ISSUE TITLE
Move from "test.pypi.org" to the real pypi.org

### ISSUE THREAD

**Issue by ctrl-z-9000-times** [htm-community/htm.core#952]
Currently we're releasing python packages to pypi's test server, not their production server. 
It would be nice if this project were located on the production server.

If it were on the production server, then installation would be  as simply as `pip install htm-core`

See file `.github/workflows/release.yaml`
Line 208-214:
```yaml
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        repository_url: https://test.pypi.org/legacy/ #TODO toggle test/real pypi
        packages_dir: ./dist/
```
